name: push

on: [push, pull_request]

env:
  GO_VERSION: "1.21.0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          stable: false

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        run: |
          go test -v -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
        env:
          CGO_ENABLED: 0

      - uses: codecov/codecov-action@v3

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          stable: false

      - uses: actions/checkout@v3

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest